# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

## zmodload zsh/zprof

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
    source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
eval "$(starship init zsh)"
eval "$(zoxide init zsh)"

export TERM="xterm-256color"

# Aliases
alias matlab="matlab -nodesktop -nosplash"
alias list="ls -ahol"

# CLI improved
alias vim="nvim"
alias ping="prettyping --nolegend"
alias ping6="prettyping -6 --nolegend"
alias top="htop"
alias du="ncdu"
alias df="duf"
function gi() { curl -sLw "\n" https://www.toptal.com/developers/gitignore/api/$@ ;}

# zsh history
export HISTFILE=~/.zsh_history   # ensure history file visibility

# additional completions
fpath=(/usr/share/zsh/site-functions $fpath)

# youtube-dl
alias yd="youtube-dl"

# fzf
source /usr/share/doc/fzf/examples/key-bindings.zsh
source /usr/share/doc/fzf/examples/completion.zsh

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ -f ~/.p10k.zsh ]] && source ~/.p10k.zsh

# zlua
# eval "$(lua ~/.zsh/zlua/z.lua --init zsh once enhanced)"
# alias z="_zlua -I"

# gnupg
export GPG_TTY=$(tty)

# go
export GOPATH=$HOME/go

export YSU_MESSAGE_POSITION="after"

# Docker
alias dry="docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock -e DOCKER_HOST=$DOCKER_HOST moncho/dry"
alias ab="podman run -dt --name archivebox --rm -p 8000:8000 -v $HOME/Nextcloud/archivebox:/data docker.io/archivebox/archivebox"

# Pipenv
eval "$(pipenv --completion)"

# ripgrep
alias rg="rg -p"

# kitty
kitty + complete setup zsh | source /dev/stdin

## zprof
